---
- name: yum clean metadata
  command: yum clean metadata 
  args: 
    warn: no
- name: restart firewalld
  service: name=firewalld state=restarted
- name: restart logstash
  service: name=logstash state=restarted
